### ISSUE TITLE
함수형 프로그래밍 궁금한 부분, 챕터 1내용 논의

### ISSUE THREAD

**Issue by wo-o29** [FEBookStudy/functional-javascript-programming#3]
### Q1. 커링을 사용해보신 경험이 있으신가요??

<img width="726" alt="스크린샷 2024-11-29 오후 10 45 05" src="https://github.com/user-attachments/assets/ffe32438-ff11-40f1-907c-6063ccb671fb">

*사진 출처 - 함수랑 산악회 - 쑥쑥쑥쑥 스터디(테오 연사)*

***

### Q2. 코드 짤 때 클래스 문법을 자주 사용하시나요?
- 저는 거의 자바스크립트로 프로그래밍을 입문해서 그런지 잘 모르기도 하고 주로 사용하지 않는 것 같네요~

***

### Q3. 주니어 개발자가 회사에서 이런식(함수형 도구 적극 사용 및 함수형 패러다임 도입 등)으로 하자고 어필을 할 수 있는 분위기인가요?? 
- (물론 회사 by 회사일 것 같긴한데 다니시는 회사는 어떤 편이신가요?)

<img width="735" alt="스크린샷 2024-11-29 오후 10 43 26" src="https://github.com/user-attachments/assets/0f4bcc1c-1aaf-4ff0-8858-eb592d8987a7">

*사진 출처 - 함수랑 산악회 - 쑥쑥쑥쑥 스터디(테오 연사)*

***

### Q4. 다른분들은 함수형 프로그래밍을 깊게 배워서 얻고싶은 부분이 무엇이신가요~?

저는 사실 위에서 말한 제너레이터, pipe, currying등을 공부하면 나중에 잘써먹지 않을까? 라는 생각이 있었는데 막상 테오의 얘기나 같이 동아리 하시는 분들 말씀 들어보면 오히려 이렇게 코드를 짜는 사람과는 협업하기 어렵다는 답변이 많은 것 같아서 함수형 프로그래밍을 깊게 팠을 때 어떤 장점이 있을까? 라는 생각이 드는 것 같네요🤔

- 막상 반대 입장에서 내가 함수형 프로그래밍을 학습하지 않았는데 같이 일하는 동료가 `이해하기 어려운 함수형 코드` 를 사용하고 있으면 `흐음… 굳이 사용해야 하나요?` 와 같은 답변을 할 것 같은 느낌이…(함수형 프로그래밍을 썼을 때 드라마틱한 효과가 나타나는건 아니여서 제너레이터 이런거 사용하자고 상대방을 설득하기가..)
- 물론 쏙쏙 들어오는 함수형 코딩 읽고 함수형 사고? 약간 자바스크립트 특유의 유연한 사고 방식을 할 수 있어서 좋았던 것 같아요! 근데 이걸 더 깊게 팠을 때의 이점에 대해서 고민이 되는 것 같아서 다른 분들은 어떤 목표가 있으신지 궁금하네요(지연 평가는 재밌을지도..?)

***

### Q5. `identity` 함수를 마땅히 사용할 곳이 떠오르지 않는데 다른 분들 생각은 어떠신가요~?

```tsx
// p22
const filter = (list, predicate) => {
  const newList = [];
  for (let i = 0; i < list.length; i++) {
    if (predicate(list[i])) {
      newList.push(list[i]);
    }
  }
  return newList;
};

const identity = (v) => v;
const arr = [true, false, 10, 0];
console.log(filter(arr, identity)); // [true, 10]

```

***

### Q6. 저는 개인적으로 `Boolean` 방식이 더 이해하기 쉽고 의도가 명확하다고 생각하는데 어떻게 생각하시나요??

```tsx
// p22
_.truthy = (v) => !!v; // 성능은 이게 더 좋다고 하는데 미세한 차이일 것 같다..
_.truthy = (v) => Boolean(v);
```

**Comment by devwontory** [comment]
A1. 저는 사용해본 경험은 없는 것 같아요. 하지만 여러 라이브러리들의 소스 코드를 살펴보면 심심치 않게 커링이 발견되더라구요. 그리고 이번 챕터를 읽으면서 클로저와 함께 사용했을 때 커링의 시너지가 정말 좋다고 느꼈어요. (그리고 왠지 모르게 섹시해보이지 않나요 ㅋㅋㅋㅋ)

A2. 전 리액트로 자바스크립트에 입문해서 Error boundary를 제외하고는 자바스크립트에서 클래스를 접해본 경험은 없는 것 같아요. 더군다나 Next.js에서는 Error boundary 처리를 이미 해주고 있어서 더욱 사용할 일이 없더라구요. 저는 오히려 이 부분에서 약점이라고 느껴서 나중에라도 꼭 공부해보려고 합니다!

A4. 저는 스스로 깔끔한 코드를 작성하는 것에 큰 관심이 있어요. 함수형이 이 부분을 충족시켜줄 수 있는 수단 중 하나인 것 같아서 흥미도 가구요! 불변성을 잘 지키고 부수효과를 잘 다루는 것이 함수형의 메인 목적이라고 생각하지만, 저는 코드의 가독성 측면에서 함수형 프로그래밍이 더 매력적으로 다가오는 것 같습니다.

A5. 책의 예시로도 나왔지만, 개인적으로는 알고리즘 문제들을 풀 때 falsy 값들을 필터링할 때 가끔 이런 코드를 작성하게 되는 것 같아요. `arr.filter((v) => v));` 그런 측면에서 아예 의미가 없는 함수는 아니라고 생각합니다.

A6. 저도 Boolean으로 처리하는 것이 더 명확하게 의미 전달이 된다고는 생각하지만, `!!v`가 가독성을 크게 해치는 수준까지는 아니라고 생각해요. 그래서 정말 성능적으로 중요하고 벤치마킹 점수를 올리는 것이 핵심인 경우에는 `!!v`를 사용할 수도 있을 것 같습니다!

**Comment by holim0** [comment]
Q6에 대해서 성능차이가 얼마나 날지 궁금해서 GPT한테 코드 짜달라고 해봤습니다.

```js
const testCases = [
  0,
  1,
  "",
  "string",
  null,
  undefined,
  true,
  false,
  [],
  [1],
  {},
  { key: "value" },
];

function truthyDoubleNegation(v) {
  return !!v;
}

function truthyBoolean(v) {
  return Boolean(v);
}

// Measure performance for double negation
console.time("Double Negation");
for (let i = 0; i < 1000000; i++) {
  for (let v of testCases) {
    truthyDoubleNegation(v);
  }
}
console.timeEnd("Double Negation");

// Measure performance for Boolean
console.time("Boolean Constructor");
for (let i = 0; i < 1000000; i++) {
  for (let v of testCases) {
    truthyBoolean(v);
  }
}
console.timeEnd("Boolean Constructor");
```

### 결과
>Double Negation: 19.697ms
>Boolean Constructor: 9.967ms

**Comment by devwontory** [comment]
> Q6에 대해서 성능차이가 얼마나 날지 궁금해서 GPT한테 코드 짜달라고 해봤습니다.
> 
> ```js
> const testCases = [
>   0,
>   1,
>   "",
>   "string",
>   null,
>   undefined,
>   true,
>   false,
>   [],
>   [1],
>   {},
>   { key: "value" },
> ];
> 
> function truthyDoubleNegation(v) {
>   return !!v;
> }
> 
> function truthyBoolean(v) {
>   return Boolean(v);
> }
> 
> // Measure performance for double negation
> console.time("Double Negation");
> for (let i = 0; i < 1000000; i++) {
>   for (let v of testCases) {
>     truthyDoubleNegation(v);
>   }
> }
> console.timeEnd("Double Negation");
> 
> // Measure performance for Boolean
> console.time("Boolean Constructor");
> for (let i = 0; i < 1000000; i++) {
>   for (let v of testCases) {
>     truthyBoolean(v);
>   }
> }
> console.timeEnd("Boolean Constructor");
> ```
> 
> ### 결과
> > Double Negation: 19.697ms
> > Boolean Constructor: 9.967ms

오잉 Boolean이 훨씬 빠르네요?
어쩌면 V8에서 이 부분에 대해서 최적화가 되어있을 것 같아서 그런 것 같네요!

**Comment by wo-o29** [comment]
https://www.sitepoint.com/javascript-double-negation-trick-trouble/
https://stackoverflow.com/questions/15335452/why-is-boolean-so-slow-in-javascript
이 글들 보니깐 최근에는 `Boolean`이 더 빨라졌다고 하는 것 같네요 신기하넴..

**Comment by holim0** [comment]
@wo-o29 12/15 스터디 진행할 때 다시 논의해봐요!
