### ISSUE TITLE
[Chapter 1] 커링의 실용성에 대해 어떻게 생각하시나요?

### ISSUE THREAD

**Issue by holim0** [FEBookStudy/functional-javascript-programming#4]
## 챕터 정보
- 챕터 번호: Chapter 1
- 페이지 범위: 45p

#### 관련 코드(optional)
```js
const add = (a) => (b) => {
	return a+b
}

const add10 = add(10)
add(20)
```

## 참고 자료
- https://ko.javascript.info/currying-partials

**Comment by wo-o29** [comment]
저는 아직 코드 작성할 때 `커링을 사용하자`라는 사고가 안떠오르는 것 같고, 되게 유용하게 쓰일 유즈 케이스를 못찾은 느낌인 것 같습니다~

희제님이 커링 방식이 사용하셨을 때 `아 이거 커링써서 좋았다` 싶은 유즈 케이스가 있으실까요??

**Comment by holim0** [comment]
> 저는 아직 코드 작성할 때 `커링을 사용하자`라는 사고가 안떠오르는 것 같고, 되게 유용하게 쓰일 유즈 케이스를 못찾은 느낌인 것 같습니다~
> 
> 희제님이 커링 방식이 사용하셨을 때 `아 이거 커링써서 좋았다` 싶은 유즈 케이스가 있으실까요??

저는 부모-자식 관계에서의 컴포넌트에서 사용했던 경험이 있었습니다.

부모에서 특정 인자를 먼저 바인드 해준 상태에서 자식 컴포넌트만이 가지고 있는 나머지 인자를 넣어서 함수를 실행해야 되는 상황이라 커링을 사용했습니다.

일단 bind를 사용했다가 그 당시에 커링 방식을 알게되어서 적용했어요!

**Comment by holim0** [comment]
논의 완료로 이슈 닫겠습니다! 추가 의견 있다면 다시 열어주세요
