### ISSUE TITLE
[Chapter 1]  '함수형 자바스크립트 소개' 발표 후 내용 논의 질문

### ISSUE THREAD

**Issue by onlyoon** [FEBookStudy/functional-javascript-programming#6]
### Q 1. 

저는 함수형 프로그래밍이 일구는 바가

> 프로그램을 완벽하게 완성하는 그 과정에서 최대한 오류를 줄이기 위한 패러다임

이라고 생각을 했으며 이 오류(부수효과)를 줄이기 위해서

- 일급 함수
- 클로저
- 고차 함수
- 보조 함수
- 리턴 함수 부분 적용

과 같은 개념들이 사용된다고 생각했는데요. 다른 분들은 어떻게 생각하시나요?

### Q 2.

아래 `1-43` 예제 코드를 보면 `f4`가 실행되는 시점에서만 `f5`는 클로저가 되었지만
아래 `1-44` 예제 코드를 보면 `f6`가 실행되는 시점 이외에도 `f7`은 클로저로 남아 있었다고 합니다.

두 코드의 가장 큰 차이는 `var f8 = f6();` 특정 변수가 기존의 선언된 함수를 참조한 것인데요.
이 차이로 인해 왜 `f6`은 클로저로 남아있을 수 있었을까요?

##### [코드 예제 1-43]
```javascript
function f4() {
  var a = 10;
  var b = 20;
  function f5() {
    return a + b;
  }
  return f5();
}
f4();
// 30
```

##### [코드 예제 1-43]
```javascript
function f6() {
  var a = 10;
  function f7(b) {
    return a + b;
  }
  return f7;
}
var f8 = f6();
f8(20);
// 30
f8(10);
// 20
```

### Q 3. 

저자는 브라우저는 함수 내부가 아닐 경우 모두 글로벌 스코프지만, Node.js에서 사용하는 js 파일 하나의 스코프는 글로벌 스코프가 아니라고 하는데요. 

그러면 모듈 단위의 렉시컬 스코프는 어떻게 할당되는 걸까요?

### Q 4. 

고차 함수를 사용할 수록 복잡성이 늘어난다는 우려도 있는데요. 

하나의 함수에 다양한 기능이 들어갈 수록 점점 더 코드를 이해하는데 어려움이 생기는 것 같습니다. 

고차 함수는 함수형 프로그래밍에서 꼭 필요한 개념 중에 하나인데요.

함수형 프로그래밍을 활용하기 위해서 이러한 복잡성을 줄이는 방법은 어떤 것이 있을까요?

### Q 5.

저는 익명 함수가 넘겨지는 것을 보면 항상 콜백 함수라고 칭하는 경향이 있었는데요.
저자는 콜백 함수는 반드시 익명 함수일 필요도 없으며, 익명 함수가 넘어가는 모양을 가졌다고 반드시 콜백 함수는 아니라고 합니다. 

다른 분들은 콜백 함수를 어떻게 정의 내리시나요?

**Comment by devwontory** [comment]
A1.
> 오류(제어되지 않은 부수효과)를 줄이기 위해 불변성을 활용한다.
> 다형성(재사용성이 높은 함수)을 위해 일급 함수, 클로저 등의 개념을 활용한다.

위와 같이 이해했습니다.

A2.
f6은 클로저인 f7을 반환하는 함수로, f8에는 변수 a의 값인 10을 기억하고 있는 f7 함수(클로저)가 저장됩니다. 변수에 할당했다는 점에서 1-43 코드와 다릅니다. 1-43의 f5는 f4의 실행이 종료됨에 따라 즉시 Garbage Collection의 대상이 됩니다. 하지만 f6의 반환값(일급)인 f7은 f8 변수에 할당했기 때문에 메모리에 남아있게 되고, 모듈 안에서 언제든지 불러와 사용할 수 있습니다.

**Comment by wo-o29** [comment]
1. 저도 동일하게 생각합니다~

`쏙쏙 들어오는 함수형 코딩` 책에서 함수형 프로그래밍의 정의를 `부수 효과 없이 순수 함수(Pure Function)만 사용하는 프로그래밍 스타일` 이렇게 설명해주고 있는데 사실 실제 프로그래밍에서 부수 효과를 사용하지 않을 수 없기 때문에 `함수형 프로그래밍은 부수 효과를 잘 다뤄서 예측 가능한 코드를 작성하는 패러다임`이라고 생각했던 것 같아요~ 

2. 요 부분은 성원님이 잘 설명해주신 것 같네요 저도 배워갑니다🙇‍♂️

3. 이 부분에 대해서는 무지한 것 같네요..🤔

4. 맞아요 함수형 프로그래밍을 사용하면 로직이 잘 나눠지고 추상화되면서 함수가 많아져서 복잡할 수도 있다고 생각이 드는 것 같아요.

저는 복잡도를 줄이기 위해 불필요한 추상화를 하지 않으려고 하는 것 같아요. 추상화를 했을 때의 이점은 추후 유지보수성이 좋아지고 유연하게 동작할 수 있다는 장점이 있지만 사실 변경점이 생길지 안생길지는 아무도 모르기 때문에 처음부터 추상화를 많이해서 복잡도를 올리는게 더 좋지 않다고 생각을 해서 성급한 추상화를 하지 않으려고 하는 것 같아요.(적절한 추상화라는게 참 어려운 것 같은데 딱 봤을 때 과하게 추상화하지 않는 정도로 하는 것 같아요!)

그리고 요즘은 인터페이스도 조금 신경써서 작성 하려고 하는 것 같아요(선언적인 방식? 필요한 정보를 외부 인터페이스에 노출시키고 불필요한 정보를 추상화하는?)

5. 저는 콜백함수를 다른 함수에 인자로 전달되는 함수라고 생각했던 것 같아요(특정 로직을 실행하고 인자로 넘겨준 함수를 호출하는?)

> 이번주에는 일정이 있어서 스터디에 참여하지 못해서 인사를 못드렸네요..ㅎㅎ 다음주에 뵙겠습니다~

**Comment by holim0** [comment]
### A1 

저도 윗분들의 의견과 동일하게 생각합니다.

추가로 오류와 부수효과(Side Effect)는 다른 개념이라고 생각을 해요.

- 부수 효과: 함수 내에서 어떤 구현이나 로직이 외부에 영향을 끼치는 경우 이를 부수 효과라고 생각합니다.

즉, 부수 효과가 없고 오로지 동일한 입력에 대해 동일한 값을 리턴하는 함수가 순수 함수인 것 같아요.

개발자 입장에서는 부수 효과가 많이 있다면 예측하기 어려울 것이고 이로 인해 예측 불가능한 `오류`가 발생하는거라 생각합니다.

>**즉, 성원님이 말씀주신 것처럼 함수 내에서 외부에 영향을 미치지 않기 위해 불변성을 활용(카피 온 라이트, 방어적 복사)하고** 
>**이런 함수들을 조합해서 복잡한 로직을 구성하는데 일급 함수, 클로저, 고차 함수 등의 개념이 사용될 것 같습니다.**

### A2

클로저 존재 여부의 차이가 변수로의 할당때문에 발생하는 것은 아니라고 생각해요

```js
function f4() {
  var a = 10;
  var b = 20;

  function f5() {
    return a + b; // f5는 외부 함수 f4의 변수 a, b에 접근
  }

  return f5(); // f5 함수를 호출하고 그 결과를 반환
}
```
f5 함수는 `return f5()`로 호출만 되고 반환되지 않기 때문에(결과값이 반환), f5가 실행된 후 외부 변수 a, b에 대한 참조가 더 이상 남아 있지 않습니다.

클로저는 f5가 호출될 때 생성되지만, 호출이 끝난 후 더 이상 내부 함수가 유지되지 않으므로 클로저도 사라질 것 같아요. 변수 `a` 와 `b`는더이상 본인들을 참조하는 곳이 없기 때문에 가비지 컬렉션 대상이 되겠네요.

반면 `f5` 함수 자체를 반환하면 클로저가 계속 유지 될 것 같습니다.

### A3

`렉시컬 스코프의 할당` 해당 말이 어떤 말인지 이해가 되지 않아서 다시 설명해주실 수 있을까요? 어떤 의도로 말씀주셨는지 궁금해요. (@onlyoon)

일단 제가 이해한 바로 의견을 남겨볼게요. (자바스크립트는 렉시컬 스코프(Lexical Scope)를 따른다. <-- 이 문장으로 이해했어요)

1. 브라우저에서의 글로벌 스코프
- 브라우저에서 글로벌 스코프는 window 객체
- 함수 밖에서 선언된 변수는 기본적으로 window 객체의 속성으로 할당

```js
var a = 10;
console.log(window.a); // 10
```

2. Node.js에서의 파일 스코프
- Node.js에서는 JavaScript 파일 하나가 모듈 단위의 스코프로 실행
- Node.js에서 함수 외부에 작성된 코드는 전역 스코프에 직접 접근하지 않고, 모듈 스코프(파일 스코프)로 감싸짐

```js
// example.js
var a = 10;
console.log(global.a); // undefined
console.log(a); // 10
```
Node.js는 모든 파일을 즉시 실행 함수(IIFE) 로 감싸서 실행한다고 합니다. ([Module Wrapper](https://nodejs.org/api/modules.html#modules_the_module_wrapper)라고 합니다.)

```js
(function (exports, require, module, __filename, __dirname) {
      var a = 10;
      console.log(a);
 })()
```
따라서, 각 파일 단위로 독립적인 스코프를 가지게 됩니다.

### A4

각 함수는 단일 책임 원칙(Single Responsibility Principle)을 따르게 구성하고 순수 함수로 구현한다면 각 함수의 하는 역할이 확실해 지기 때문에 어느정도 복잡성을 해결할 수 있지 않을까 생각을 해요.

중첩되는 고차 함수에서 인자로 전달되는 함수의 이름 또한 명확하면 괜찮지 않을까 싶어요. 

또한 불필요한 추상화를 하게 되면 복잡해지기 때문에 전 일단 그냥 개발을 먼저 하고 개발하면서 계속 불편함이 보인다면 개선할거 같아요.


### A5

저는 인자로 넘겨지는 함수를 콜백함수라고 불렀던 것 같아요. 

https://developer.mozilla.org/ko/docs/Glossary/Callback_function

---

올려주는 논의 사항으로 덕분에 저도 다시 공부하게 되었네요. 감사합니다! 👍

**Comment by onlyoon** [comment]
> 오류(부수효과)를 줄이기 위해 불변성을 활용한다.
> 다형성(재사용성이 높은 함수)을 위해 일급 함수, 클로저 등의 개념을 활용한다.

단순히 오류를 줄이기 위해서만을 사용하는 것이 아닌 다형성을 위해 일급 함수 및 클로저 등의 개념을 활용하는 것 또한 있겠네요.
함수형 프로그래밍 패러다임을 좀 더 넓게 바라봐야 할 것 같습니다.

> f6은 클로저인 f7을 반환하는 함수로, f8에는 변수 a의 값인 10을 기억하고 있는 f7 함수(클로저)가 저장됩니다. 변수에 할당했다는 점에서 1-43 코드와 다릅니다. 1-43의 f5는 f4의 실행이 종료됨에 따라 즉시 Garbage Collection의 대상이 됩니다. 하지만 f6의 반환값(일급)인 f7은 f8 변수에 할당했기 때문에 메모리에 남아있게 되고, 모듈 안에서 언제든지 불러와 사용할 수 있습니다.

이번주에 스터디를 해오면서 가장 크게 배웠던 부분이 이 부분인 것 같습니다.
클로저라는 이 함수가 언제 생성되고  언제 사라지는지를 파악할 수 있었는데요.

알려주신 덕분에 1-43과 1-44의 예시에서 클로저가 담긴 함수가 다른 변수에 참조됨에 따라서 실행 된 이후에도 Garbage Collection의 대상이 되지 않았다는 것을 알 수 있었네요.

덕분에 많이 배웠습니다~

**Comment by onlyoon** [comment]
> `쏙쏙 들어오는 함수형 코딩` 책에서 함수형 프로그래밍의 정의를 `부수 효과 없이 순수 함수(Pure Function)만 사용하는 프로그래밍 스타일` 이렇게 설명해주고 있는데 사실 실제 프로그래밍에서 부수 효과를 사용하지 않을 수 없기 때문에 `함수형 프로그래밍은 부수 효과를 잘 다뤄서 예측 가능한 코드를 작성하는 패러다임`이라고 생각했던 것 같아요~

맞아요. 부수 효과를 없애기 위해 아주 완벽한 순수 함수 위주로만 프로젝트의 코드가 작성될 때 개인적으로 제 생각은, 그 규칙 하나를 지키기 위해 로직이나 개발 복잡도가 올라가지 않을까 예상을 하고 있어서, 부수 효과를 완벽하게 지운다기보다는 함수를 작성할때 그러한 부분들을 인지를 하며 특정 로직이나 오류가 없어야 하는 부분에서 활용할 때 그리고 재사용성까지 가져가고 싶을 때, 효과가 뛰어난 패러다임이라고 생각을 하는 것 같아요.

> 저는 콜백함수를 다른 함수에 인자로 전달되는 함수라고 생각했던 것 같아요(특정 로직을 실행하고 인자로 넘겨준 함수를 호출하는?)

저도 인자로 넘겨지는 모든 함수를 콜백함수라고 칭했던 것 같은데, 책의 저자분께서 다른 의견을 알려주셨었어요.

```javascript
button.click(function() {})
```

위와 같은 익명 함수는 `callback`라기보다는 `event listener`에 적합하다고 하시더라구요.

```javascript
_.each([1,2,3], function () {})
```
해당 부분의 익명 함수도 `callback`이 아닌 `iteratee`다. 라는 얘기가 있는데

해당 책의 저자 분께서 말씀하시는 부분은, 콜백함수는 종료될 때 단 한 번 실행되는 것이며, 그렇지 않은 것들은 다르게 칭하는 것이 알맞다고 얘기하시더라구요.

@holim0  @wo-o29 이 부분 관련해서 의견 궁금해서 `mention`할께요!

> 안녕하세요 우혁님, 의견 나눠주셔서 감사합니다. 이번주에 봬요!

**Comment by wo-o29** [comment]
> 저도 인자로 넘겨지는 모든 함수를 콜백함수라고 칭했던 것 같은데, 책의 저자분께서 다른 의견을 알려주셨었어요.
> 
> ```js
> button.click(function() {})
> ```
> 
> 위와 같은 익명 함수는 `callback`라기보다는 `event listener`에 적합하다고 하시더라구요.
> 
> ```js
> _.each([1,2,3], function () {})
> ```
> 
> 해당 부분의 익명 함수도 `callback`이 아닌 `iteratee`다. 라는 얘기가 있는데
> 

모던 자바스크립트 딥 다이브 책에서 콜백 함수의 정의를 `함수의 매개변수를 통해 다른 함수의 내부로 전달되는 함수를 콜백 함수라고 한다.` 라고 소개해주고 있어서 제가 생각하기에는 콜백 함수가 큰 범위이고, 그 안에 콜백 함수 중에서도 `event listener`, `iteratee` 라고 조금 더 정확하게 표현하는 것 같다고 생각했던 것 같아요! 
```js
// 요런 느낌..?
🎯 콜백 함수
 ┣ 👉 event listener
 ┣ 👉 iteratee
```

그래서 제가 생각한 결론은 저 함수들이 실제로 콜백 함수이기도 하고, 조금 더 정확한 표현이 있지만 콜백 함수라고 불러도 같이 일하는 동료가 맥락 을 파악하지 못할 정도는 아니라고 생각을 해서 가볍게 넘어갔던 것 같네요:) 

> 해당 책의 저자 분께서 말씀하시는 부분은, 콜백함수는 종료될 때 단 한 번 실행되는 것이며, 그렇지 않은 것들은 다르게 칭하는 것이 알맞다고 얘기하시더라구요.

저자분도 `필자는 위 경우만을 '콜백' 함수라고 부르는 것이 맞다고 생각한다.` 라고 본인의 생각을 전달하고, 그 근거로 `표현의 제약은 상상력에도 제약을 만든다. 모든 익명 함수는 콜백 함수가 아니다. 각 함수에서 사용될 보조 함수에게도 역할에 가장 맞는 이름이 있는 것이 좋다.`라고 작성해 주셔서 
저는 `이게 정답이다` 라기보다는 `나는 ~~~한 이유로 ~~~ 이렇게 생각한다` 정도로 받아들였던 것 같아요🙃

**Comment by onlyoon** [comment]
> 추가로 오류와 부수효과(Side Effect)는 다른 개념이라고 생각을 해요.
> 
> * 부수 효과: 함수 내에서 어떤 구현이나 로직이 외부에 영향을 끼치는 경우 이를 부수 효과라고 생각합니다.
> 
> 즉, 부수 효과가 없고 오로지 동일한 입력에 대해 동일한 값을 리턴하는 함수가 순수 함수인 것 같아요.
> 
> 개발자 입장에서는 부수 효과가 많이 있다면 예측하기 어려울 것이고 이로 인해 예측 불가능한 `오류`가 발생하는거라 생각합니다.

제가 `부수효과 == 오류` 라고 생각하는 경향이 있다고 생각합니다. 
부수 효과의 개념에 따라 내부의 로직이 외부에 영향을 끼쳐 예측이 어려워 오류가 발생되는 것으로 생각하는 것이 올바른 것 같아요!

저자는 브라우저는 함수 내부가 아닐 경우 모두 글로벌 스코프지만, Node.js에서 사용하는 js 파일 하나의 스코프는 글로벌 스코프가 아니라고 하는데요.

그러면 모듈 단위의 렉시컬 스코프는 어떻게 할당되는 걸까요?

> 렉시컬 스코프의 할당 해당 말이 어떤 말인지 이해가 되지 않아서 다시 설명해주실 수 있을까요? 어떤 의도로 말씀주셨는지 궁금해요. (@onlyoon)

저는 자바스크립트의 기본적인 스코핑 방식이 렉시컬 스코프라고 생각해서, 글로벌 스코프와 지역 스코프가 렉시컬 스코프 개념에 포함이 된다고 생각했던 것 같아요.
이건 제가 잘못 정의 내린 것 같은데요, 
글로벌 스코프나 지역 스코프의 경우 변수의 선언 위치에 따라서 해당 변수가 접근 가능한 범위를 나타내지만, 
렉시컬 스코프는 함수가 어디에서 선언되었는지에 따라 변수가 유효해지는 범위를 결정한다는 것을 뜻하더라구요.

그래서 문제 자체를 다시보면, 

>> 그러면 모듈 단위의 스코프는 어느정도의 변수가 접근이 가능한 범위를 나타낼까요?

로 마지막 질문을 하는 것이 옳은 질문이 될 것 같네요.

얘기해주신 각 파일 단위의 스코프를 지닌다는게 정의를 다시 보고 생각해보니 올바르다고 생각해요!

> 또한 불필요한 추상화를 하게 되면 복잡해지기 때문에 전 일단 그냥 개발을 먼저 하고 개발하면서 계속 불편함이 보인다면 개선할거 같아요.

저도 개발을 하다가 불편한 부분이 지속적으로 보이면 개선하는 수순으로 갈 것 같습니다.

**Comment by holim0** [comment]
@onlyoon 
> 저도 인자로 넘겨지는 모든 함수를 콜백함수라고 칭했던 것 같은데, 책의 저자분께서 다른 의견을 알려주셨었어요.
> 
> ```js
> button.click(function() {})
> ```
> 
> 위와 같은 익명 함수는 `callback`라기보다는 `event listener`에 적합하다고 하시더라구요.
> 
> ```js
> _.each([1,2,3], function () {})
> ```
> 
> 해당 부분의 익명 함수도 `callback`이 아닌 `iteratee`다. 라는 얘기가 있는데
> 
> 해당 책의 저자 분께서 말씀하시는 부분은, 콜백함수는 종료될 때 단 한 번 실행되는 것이며, 그렇지 않은 것들은 다르게 칭하는 것이 알맞다고 얘기하시더라구요.

저자가 말하는 의도는 좀 더 세세하게 부르자로 이해를 했습니다. 

[MDN 문서](https://developer.mozilla.org/ko/docs/Glossary/Callback_function)에도 콜백 함수는 **전달인자로 다른 함수에 전달되는 함수**라고 정의되어 있기도 해서 그냥 인자 전달되는 함수는 콜백함수다.. 이렇게 생각을 하고 있었어요

근데 저자는 인자로 전달되는 함수의 역할이 다양하고 그걸 그냥 `콜백 함수`로 부르는 것이 명확하지 않다는 입장인거 같아요. 

그래서 인자로 전달되는 함수가 가지고 있는 특성에 따라 더 명확하게 명명하는게 함수형 프로그래밍을 할 때 더 풍성하게 다룰 수 있다는 의견을 적어둔거 같아요. 

특정 함수의 로직과 관계 없이 그 함수의 로직이 완료되고 인자로 전달된 함수가 호출이 된다면 콜백 함수, 함수의 로직과 관련된 무언가 역할을 수행하는 함수일 때는 그 역할에 맞게 불러주면 되겠다! 결론내렸습니다.

책에 나온 `filter` 함수 예시를 기준으로 보면 아래와 같이 인자로 넘겨진 함수는 콜백 함수가 맞으니 이런 생각을 기반으로 명칭도 `callback`으로 하면 명확하게 이해하기 어려울거 같아요.
```js
function filter(list, callback) {
  var new_list = [];
  for (var i = 0, len = list.length; i < len; i++) {
    if (callback(list[i])) new_list.push(list[i]);
  }
  return new_list;
}

const users_under_30 = filter(users, (user) => user.age < 30);

console.log(users_under_30.length);
```

근데 콜백 함수가 명확하게 어떤 역할을 하는지에 대해 표현이 되어 있다면 더 잘 이해할 수 있을거 같아요!
`predicate`는 콜백 함수가 맞긴하지만 더 구체적으로 생각해보자. <- 이런 의도도 이해했어요
```js
function filter(list, predicate) {
  var new_list = [];
  for (var i = 0, len = list.length; i < len; i++) {
    if (predicate(list[i])) new_list.push(list[i]);
  }
  return new_list;
}

const users_under_30 = filter(users, (user) => user.age < 30);

console.log(users_under_30.length);
```
